### ISSUE TITLE
Support replacing 'you' with person name

### ISSUE THREAD

**Issue by zdenek-crha** [paulfitz/exoplanets#1]
The web page is hilarious. The only thing it is missing is ability to pass person name via url. 

I would like to send link to page with *'MY NAME'* birthdays and I don't want people to be confused about whom they should give presents just because it shows *'you'* on the page.

Example: 
Link `http://exo.makesweet.com/1982/6/1/MY%020NAME` would generate page with 'MY NAME' instead of 'you' in the planet image. 

I assume it should not be hard to do, since you already render 'Ursula leGuin' name as example. I've been looking for way to pass my name into page but found it is probably hardcoded.

**Comment by paulfitz** [comment]
@zdenek-crha I tweaked the site to support your links http://exo.makesweet.com/1982/6/1/MY%20NAME - enjoy.

**Comment by zdenek-crha** [comment]
@paulfitz Amazing! Thank you very much.
